services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - authservice
      - micropostservices
      - worthreadingservice
      - micro-url-shortener-service
      - imageService
      - userService

  authservice:
    image: ghcr.io/chatgut/authservice2:latest
    depends_on:
      - authservice-mysql
    container_name: authservice2
    ports:
      - "8003:8080"
    environment:
      DB_URL: authservice-mysql:3306/authservice-mysql
      DB_USER: developer
      DB_PASS: password

  authservice-mysql:
    image: 'mysql:latest'
    container_name: authservice2-mysql
    volumes:
      - db_auth:/var/lib/mysql
    environment:
      MYSQL_DATABASE: authservice-mysql
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"

  micropostservices:
    image: ghcr.io/chatgut/micropostservice:main
    container_name: microPostServices
    restart: on-failure
    depends_on:
      - mongodb
      - rabbitMQ
    environment:
      ROCKET_DATABASES: '{postservice={url="mongodb://dbMongoDB:27017"}}'
      ROCKET_RABBIT_HOST: "amqp://QueueRabbitMQ:5672"
    ports:
      - "8000:8000"

  mongodb:
    image: 'mongo:latest'
    container_name: dbMongoDb
    volumes:
      - db_mongoPost:/data/db
    ports:
      - "27017:27017"

  rabbitMQ:
    image: 'rabbitmq:3-management'
    container_name: QueueRabbitMq
    volumes:
      - db_rabbitPost:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  worthreadingservice:
    image: ghcr.io/chatgut/worthreadingservice:master
    container_name: worthreadingService
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/demo
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8005:8005"

  mysql:
    image: 'mysql:latest'
    container_name: mysqlDB
    volumes:
      - dbWR:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    ports:
      - '3305:3306'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5

  micro-url-shortener-service:
    image: ghcr.io/chatgut/micro-url-shortener-service:main
    container_name: micro-url-shortener
    restart: on-failure
    ports:
      - "8004:8004"
    depends_on:
      - mongodbMicroUrl
    environment:
      APP_DOMAIN_NAME: http://localhost:8004/
      MONGO_DB_URI: mongodb://mongodbMicroUrl:27017

  mongodbMicroUrl:
    image: mongo:6.0.5
    container_name: mongodbMicroUrl
    volumes:
      - db_MicroUrl:/data/db
    ports:
      - "27018:27017"

  imageService:
    image: ghcr.io/chatgut/imageservicebov:sha-925024f
    depends_on:
      - imageService-mysql
    ports:
      - "8001:8001"
    environment:
      DB_URL: imageservice-mysql:3306/imageservice-mysql
      DB_USER: developer
      DB_PASS: password
  imageService-mysql:
    image: "mysql:latest"
    container_name: imageService-mysql
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: imageservice-mysql
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"

  userService:
    image: ghcr.io/chatgut/userservice:1.0
    container_name: userService
    ports:
      - "8002:8002"
    depends_on:
      - dbUsers
    environment:
      DB_URL: jdbc:mysql://dbUsers:3306/userService
      DB_USER: developer
      DB_PASSWORD: password

  dbUsers:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userService
      MYSQL_PASSWORD: password
      MYSQL_USER: developer
    volumes:
      - dbUsers:/var/lib/mysql
    ports:
      - "3308:3306"
volumes:
  db_auth:
  dbUsers:
  db_mongoPost:
  db_rabbitPost:
  db_MicroUrl:
  dbWR:
  db_mysql: